apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-node-sample-multi-component-example-main-7naf
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-node-sample-multi-component-example-main-7naf
    app.kubernetes.io/part-of: multi-component-application
  name: devfile-node-sample-multi-component-example-main-7naf
  namespace: e2e-demo-ysnb
spec:
  port:
    targetPort: 3001
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: devfile-node-sample-multi-component-example-main-7naf
    weight: 100
status: {}
